# This is a basic workflow to help you get started with Actions

name: Test zarr/n5 implementation compatibility

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup conda
      uses: s-weigand/setup-conda@v1.0.2
      with:
        python-version: 3.7
        conda-channels: conda-forge

    - name: Install dependencies
      run: |
        conda create -c conda-forge -n test-env pip z5py zarr pytest scikit-image
        source activate test-env
        pip install pyn5

    # Runs a single command using the runners shell
    - name: Test compatibility
      run: |
        source activate test-env 
        make test
